from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
from langdetect import detect, LangDetectException

model_name = "facebook/nllb-200-distilled-600M"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Comprehensive NLLB-200 language mapping
LANGUAGE_NAMES = {
    "ace_Arab": "Acehnese (Arabic)",
    "ace_Latn": "Acehnese (Latin)",
    "acm_Arab": "Mesopotamian Arabic",
    "acq_Arab": "Ta'izzi-Adeni Arabic",
    "aeb_Arab": "Tunisian Arabic",
    "afr_Latn": "Afrikaans",
    "ajp_Arab": "South Levantine Arabic",
    "aka_Latn": "Akan",
    "amh_Ethi": "Amharic",
    "ang_Latn": "Old English",
    "apc_Arab": "North Levantine Arabic",
    "arb_Arab": "Modern Standard Arabic",
    "ars_Arab": "Najdi Arabic",
    "art_Latn": "Artificial Language",
    "asm_Beng": "Assamese",
    "ast_Latn": "Asturian",
    "awa_Deva": "Awadhi",
    "ayn_Arab": "Aynu",
    "aze_Latn": "Azerbaijani",
    "azb_Arab": "South Azerbaijani",
    "ban_Latn": "Balinese",
    "bel_Cyrl": "Belarusian",
    "bem_Latn": "Bemba",
    "ben_Beng": "Bengali",
    "bho_Deva": "Bhojpuri",
    "bjn_Latn": "Banjar (Arabic)",
    "bpy_Beng": "Bishnupriya",
    "bul_Cyrl": "Bulgarian",
    "cat_Latn": "Catalan",
    "ceb_Latn": "Cebuano",
    "ces_Latn": "Czech",
    "cjk_Latn": "Chokwe",
    "ckb_Arab": "Central Kurdish",
    "crh_Latn": "Crimean Tatar",
    "cym_Latn": "Welsh",
    "dan_Latn": "Danish",
    "deu_Latn": "German",
    "dik_Latn": "Dinka",
    "dyu_Latn": "Dyula",
    "ell_Grek": "Greek",
    "eng_Latn": "English",
    "enm_Latn": "Middle English",
    "epo_Latn": "Esperanto",
    "est_Latn": "Estonian",
    "eus_Latn": "Basque",
    "ewe_Latn": "Ewe",
    "fao_Latn": "Faroese",
    "fij_Latn": "Fijian",
    "fin_Latn": "Finnish",
    "fon_Latn": "Fon",
    "fra_Latn": "French",
    "frm_Latn": "Middle French",
    "fro_Latn": "Old French",
    "fur_Latn": "Friulian",
    "fuv_Latn": "Nigerian Fulfulde",
    "gaz_Latn": "West Central Oromo",
    "gba_Latn": "Gbaya",
    "gon_Deva": "Gondi",
    "gos_Latn": "Gronings",
    "got_Goth": "Gothic",
    "grn_Latn": "Guarani",
    "guj_Gujr": "Gujarati",
    "gun_Latn": "Gun",
    "gur_Latn": "Frafra",
    "guz_Latn": "Gusii",
    "hak_Hani": "Hakka Chinese",
    "hal_Latn": "Halh Mongolian",
    "hau_Latn": "Hausa",
    "heb_Hebr": "Hebrew",
    "hin_Deva": "Hindi",
    "hne_Deva": "Chhattisgarhi",
    "hrv_Latn": "Croatian",
    "hun_Latn": "Hungarian",
    "hye_Armn": "Armenian",
    "ibo_Latn": "Igbo",
    "ilo_Latn": "Iloko",
    "ind_Latn": "Indonesian",
    "isl_Latn": "Icelandic",
    "ita_Latn": "Italian",
    "jav_Latn": "Javanese",
    "jpn_Jpan": "Japanese",
    "kab_Latn": "Kabyle",
    "kac_Latn": "Kachin",
    "kam_Latn": "Kamba",
    "kan_Knda": "Kannada",
    "kas_Arab": "Kashmiri (Arabic)",
    "kas_Deva": "Kashmiri (Devanagari)",
    "kat_Geor": "Georgian",
    "kaz_Cyrl": "Kazakh",
    "kea_Latn": "Kabuverdianu",
    "khm_Khmr": "Khmer",
    "kik_Latn": "Kikuyu",
    "kin_Latn": "Kinyarwanda",
    "kir_Cyrl": "Kirghiz",
    "kmb_Latn": "Kimbundu",
    "kmr_Latn": "Kurmanji Kurdish",
    "knc_Arab": "Central Kanuri (Arabic)",
    "knc_Latn": "Central Kanuri (Latin)",
    "kod_Latn": "Kodi",
    "kok_Deva": "Konkani",
    "kor_Hang": "Korean",
    "kos_Latn": "Kosraean",
    "kpe_Latn": "Kpelle",
    "krc_Cyrl": "Karachay-Balkar",
    "krl_Latn": "Karelian",
    "krn_Latn": "Karen",
    "kru_Deva": "Kurukh",
    "ksb_Latn": "Shambala",
    "ksh_Latn": "Colognian",
    "kua_Latn": "Kuanyama",
    "kum_Cyrl": "Kumyk",
    "kur_Latn": "Kurdish",
    "kus_Latn": "Kusaiean",
    "kxp_Latn": "Konkani",
    "lad_Latn": "Ladino",
    "lam_Latn": "Lamba",
    "lao_Laoo": "Lao",
    "lij_Latn": "Ligurian",
    "lim_Latn": "Limburgish",
    "lin_Latn": "Lingala",
    "lis_Latn": "Lisu",
    "lit_Latn": "Lithuanian",
    "lmo_Latn": "Lombard",
    "lng_Latn": "Lunge",
    "lob_Latn": "Lobi",
    "loj_Latn": "Lojban",
    "lot_Latn": "Lotud",
    "loz_Latn": "Lozi",
    "lrc_Latn": "Northern Luri",
    "ltg_Latn": "Latgalian",
    "ltz_Latn": "Luxembourgish",
    "lua_Latn": "Luba-Kasai",
    "lub_Latn": "Luba-Katanga",
    "lug_Latn": "Luganda",
    "lun_Latn": "Lunda",
    "luo_Latn": "Luo",
    "lus_Latn": "Lushai",
    "lut_Latn": "Luyia",
    "luz_Latn": "Southern Luri",
    "lva_Latn": "Latvian",
    "lvk_Cyrl": "Lavkalyuk",
    "lzh_Hani": "Literary Chinese",
    "lzz_Latn": "Laz",
    "mad_Latn": "Madurese",
    "mag_Deva": "Magahi",
    "mai_Deva": "Maithili",
    "mak_Latn": "Makasar",
    "mal_Mlym": "Malayalam",
    "mar_Deva": "Marathi",
    "min_Latn": "Minangkabau",
    "mkd_Cyrl": "Macedonian",
    "pls_Latn": "Picard",
    "plt_Latn": "Plateau Signed French",
    "pnb_Arab": "Western Punjabi",
    "pop_Latn": "Poqomchi'",
    "por_Latn": "Portuguese",
    "prs_Arab": "Dari",
    "pbt_Arab": "Southern Pashto",
    "qub_Latn": "Quechua",
    "que_Latn": "South Levantine Quechua",
    "qug_Latn": "Quichua",
    "rap_Latn": "Rapa Nui",
    "roh_Latn": "Romansh",
    "ron_Latn": "Romanian",
    "rso_Latn": "Ross",
    "rua_Latn": "Rundi",
    "ruf_Latn": "Ruga",
    "run_Latn": "Rundi",
    "rus_Cyrl": "Russian",
    "rw_Latn": "Kinyarwanda",
    "sad_Latn": "Sandawe",
    "saf_Latn": "Saho",
    "sag_Latn": "Sango",
    "sah_Cyrl": "Sakha",
    "sam_Hebr": "Samaritan Hebrew",
    "san_Deva": "Sanskrit",
    "sat_Olck": "Santali",
    "scn_Latn": "Sicilian",
    "sco_Latn": "Scots",
    "sdh_Arab": "Southern Kurdish",
    "seq_Latn": "Seneca",
    "ser_Latn": "Serrano",
    "ses_Latn": "Koyraboro Senni",
    "sfi_Latn": "Sidamo",
    "sga_Latn": "Old Irish",
    "sgs_Latn": "Samogitian",
    "shi_Tfng": "Tachelhit",
    "shp_Latn": "Shipibo-Konibo",
    "sid_Latn": "Sidamo",
    "sin_Sinh": "Sinhala",
    "skr_Arab": "Saraiki",
    "slk_Latn": "Slovak",
    "slv_Latn": "Slovenian",
    "sme_Latn": "Northern Sami",
    "smj_Latn": "Lule Sami",
    "smn_Latn": "Inari Sami",
    "sms_Latn": "Skolt Sami",
    "sna_Latn": "Shona",
    "snd_Arab": "Sindhi",
    "som_Latn": "Somali",
    "sot_Latn": "Sotho",
    "spa_Latn": "Spanish",
    "spl_Latn": "Selepet",
    "srd_Latn": "Sardinian",
    "srp_Cyrl": "Serbian",
    "ssw_Latn": "Siswati",
    "ssy_Latn": "Saho",
    "sun_Latn": "Sundanese",
    "swe_Latn": "Swedish",
    "swh_Latn": "Swahili",
    "syc_Syrn": "Syriac",
    "syl_Beng": "Sylheti",
    "sym_Latn": "Symkarian",
    "syn_Latn": "Syndarin",
    "syr_Syrc": "Syriac",
    "szl_Latn": "Silesian",
    "tam_Taml": "Tamil",
    "tat_Cyrl": "Tatar",
    "tel_Telu": "Telugu",
    "tem_Latn": "Temne",
    "ter_Latn": "Tereno",
    "tet_Latn": "Tetum",
    "tgk_Cyrl": "Tajik",
    "tgl_Latn": "Tagalog",
    "tha_Thai": "Thai",
    "thi_Latn": "Thio",
    "thn_Latn": "Thao",
    "thr_Latn": "Tera",
    "Thu_Latn": "Thumbimbia",
    "tig_Ethi": "Tigre",
    "tir_Ethi": "Tigrinya",
    "tiv_Latn": "Tiv",
    "tk_Latn": "Turkmen",
    "tkl_Latn": "Tokelau",
    "tkt_Latn": "Takitaki",
    "tly_Latn": "Talysh",
    "toi_Latn": "Tonga",
    "tpk_Latn": "Tok Pisin",
    "tpo_Latn": "Toposa",
    "tps_Latn": "Pipil",
    "tpt_Latn": "Tatar Pipil",
    "tqo_Latn": "Tela-Tolo",
    "trc_Latn": "Torchwood",
    "tre_Latn": "Treen",
    "trg_Latn": "Tregami",
    "trn_Latn": "Ternate",
    "trp_Latn": "Tefé-Tukano",
    "trs_Latn": "Tristan da Cunha",
    "trt_Latn": "Tur",
    "tru_Latn": "Turoyo",
    "tsd_Grek": "Tsakonian",
    "tsi_Latn": "Tsimshian",
    "tsj_Latn": "Tshangla",
    "tsn_Latn": "Tswana",
    "tso_Latn": "Tsonga",
    "tsp_Latn": "Tosk Albanian",
    "tss_Latn": "Tswa",
    "tst_Latn": "Tristanejo",
    "tta_Latn": "Tutelo",
    "ttm_Latn": "Tutuma",
    "ttn_Latn": "Tutone",
    "tts_Latn": "Tataltepec Chatino",
    "ttu_Latn": "Tutütepeć",
    "tty_Latn": "Tutty",
    "tua_Latn": "Tümpisa Shoshone",
    "tub_Latn": "Tubalar",
    "tuc_Latn": "Mutsun",
    "tug_Latn": "Tugun",
    "tuh_Latn": "Tuhao",
    "tui_Latn": "Tairora",
    "tul_Latn": "Tula",
    "tum_Latn": "Tumbuka",
    "tup_Latn": "Tupi",
    "tur_Latn": "Turkish",
    "tuu_Latn": "Tututni",
    "tuv_Latn": "Tuvalu",
    "tuw_Latn": "Tuvatu",
    "tux_Latn": "Tuxela",
    "tuy_Latn": "Tuyuca",
    "tuz_Latn": "Tututepec",
    "tva_Latn": "Tefé-Tukano",
    "tvd_Latn": "Tuvalu",
    "tve_Latn": "Tave",
    "tvl_Latn": "Tuvalu",
    "twi_Latn": "Twi",
    "twq_Latn": "Tasawaq",
    "txb_Latn": "Txapanec",
    "txc_Latn": "Tocharian C",
    "txe_Latn": "Totoro",
    "txh_Latn": "Thracian",
    "txm_Latn": "Mixtec",
    "txo_Latn": "Tlapaanec",
    "txs_Latn": "Siuslaw",
    "txt_Latn": "Tataltepec Chatino",
    "txx_Latn": "Tatavalam",
    "txy_Latn": "Taxy",
    "tyv_Cyrl": "Tyvan",
    "tzh_Latn": "Tzeltal",
    "tzj_Latn": "Tz'utujil",
    "tzl_Latn": "Talossan",
    "tzm_Tfng": "Tamazight",
    "tzo_Latn": "Tzotzil",
    "tzz_Latn": "Tzeltal",
    "uban_Latn": "Ubangian",
    "uda_Latn": "Uda",
    "ude_Cyrl": "Udihe",
    "udm_Cyrl": "Udmurt",
    "udo_Latn": "Uduk",
    "ued_Latn": "Ued",
    "ueg_Latn": "Uele",
    "uey_Latn": "Uyghur (Latin)",
    "ufi_Latn": "Ufiomi",
    "ufo_Latn": "Ufo",
    "uga_Ugar": "Ugaritic",
    "ugg_Latn": "Ugunja",
    "ugs_Latn": "Ugandan Sign Language",
    "ugu_Latn": "Uguma",
    "uha_Latn": "Uhami",
    "uho_Latn": "Uho",
    "uhr_Latn": "Uhoromo",
    "uhw_Latn": "Uhwi",
    "uih_Latn": "Uihi",
    "uil_Latn": "Uila",
    "uin_Latn": "Uinuma",
    "uir_Latn": "Uiro",
    "uis_Latn": "Uisai",
    "uit_Latn": "Uitis",
    "uja_Latn": "Ujage",
    "uke_Latn": "Ukele",
    "uki_Latn": "Ukipa",
    "ukp_Latn": "Ukpe-Bayobiri",
    "ukq_Latn": "Ukere",
    "ukr_Cyrl": "Ukrainian",
    "uku_Latn": "Ukue",
    "ukz_Latn": "Ukeza",
    "ula_Latn": "Ulawa",
    "ulb_Latn": "Ulumanda",
    "ulc_Latn": "Ulch",
    "ule_Latn": "Ulekela",
    "ulf_Latn": "Ulufinau",
    "ulg_Latn": "Ulgon",
    "ulh_Latn": "Uliha",
    "uli_Latn": "Ulithian",
    "ulk_Latn": "Ulkokot",
    "ull_Latn": "Ulley",
    "ulm_Latn": "Ulu",
    "ulr_Latn": "Ulrichson",
    "uls_Latn": "Ulskhan",
    "ulu_Latn": "Uluma",
    "ulv_Latn": "Uluva",
    "ulw_Latn": "Uluwa",
    "ulx_Latn": "Ulexite",
    "uly_Latn": "Ulya",
    "ulz_Latn": "Ulza",
    "uma_Latn": "Umainaklo",
    "umb_Latn": "Umbundu",
    "umc_Latn": "Umecoomcut",
    "umd_Latn": "Umdanfo",
    "ume_Latn": "Umeda",
    "umf_Latn": "Umiray Dumaget",
    "umg_Latn": "Umbugarla",
    "umh_Latn": "Umhau",
    "umi_Latn": "Umin",
    "umm_Latn": "Ummanda",
    "umn_Latn": "Umundun",
    "umo_Latn": "Umotina",
    "ump_Latn": "Umpqua",
    "umq_Latn": "Umuq",
    "umr_Latn": "Umrayya",
    "ums_Latn": "Umstead",
    "umt_Latn": "Umyangite",
    "umu_Latn": "Mumuye",
    "umv_Latn": "Umvoti",
    "umw_Latn": "Umwai",
    "umx_Latn": "Umexanaklo",
    "umy_Latn": "Umyangite",
    "umz_Latn": "Umzali",
    "una_Latn": "Una",
    "unc_Latn": "Uncegilla",
    "und_Latn": "Undetermined",
    "une_Latn": "Uneme",
    "unf_Latn": "Unigena",
    "ung_Latn": "Ungarinyin",
    "unh_Latn": "Unhua",
    "uni_Latn": "Uniate",
    "unk_Latn": "Unuk",
    "unm_Latn": "Unami",
    "unn_Latn": "Unnu",
    "uno_Latn": "Uno",
    "unp_Latn": "Unapa",
    "unq_Latn": "Unquer",
    "unr_Deva": "Unruli",
    "uns_Latn": "Unserdeutsch",
    "unt_Latn": "Untera",
    "unu_Latn": "Unua",
    "unv_Latn": "Unua Volta",
    "unw_Latn": "Unwa",
    "unx_Latn": "Unxa",
    "uny_Latn": "Unye",
    "unz_Latn": "Unza",
    "uon_Latn": "Uon",
    "uor_Latn": "Uorin",
    "uos_Latn": "Uyghur-Osh Shayan",
    "uow_Latn": "Usui",
    "uox_Latn": "Uyghur-Oxus",
    "uoy_Latn": "Uyghur-Oyrat",
    "uoz_Latn": "Uyghur-Ozbekistan",
    "upa_Latn": "Upa",
    "upb_Latn": "Upland",
    "upc_Latn": "Upéchan",
    "upd_Latn": "Upd",
    "upe_Latn": "Upechan",
    "upg_Latn": "Upingtonese",
    "uph_Latn": "Uphilo",
    "upi_Latn": "Upidik",
    "upj_Latn": "Uplift",
    "upk_Latn": "Upikiro",
    "upl_Latn": "Uplander",
    "upm_Latn": "Upmaywi",
    "upn_Latn": "Upnekulela",
    "upo_Latn": "Upopa",
    "upp_Latn": "Uppalanda",
    "upr_Latn": "Upriver",
    "ups_Latn": "Upsala",
    "upt_Latn": "Uptown",
    "upu_Latn": "Upula",
    "upv_Latn": "Upvalley",
    "upw_Latn": "Upwey",
    "upx_Latn": "Upland Xavier",
    "upy_Latn": "Upyala",
    "upz_Latn": "Uptown Zona",
    "ura_Latn": "Ura",
    "urb_Latn": "Urbaani",
    "urc_Latn": "Urchon",
    "urd_Arab": "Urdu",
    "ure_Latn": "Ureña",
    "urf_Latn": "Url",
    "urg_Latn": "Urgi",
    "urh_Latn": "Urhobo",
    "uri_Latn": "Urim",
    "urj_Latn": "Ural",
    "urk_Latn": "Urkarinyin",
    "url_Latn": "Urley",
    "urm_Latn": "Urmi",
    "urn_Latn": "Urun",
    "uro_Latn": "Uro",
    "urp_Latn": "Urupa",
    "urq_Latn": "Urquacha",
    "urr_Latn": "Urarina",
    "urs_Latn": "Ursa",
    "urt_Latn": "Urtelu",
    "uru_Latn": "Uruan",
    "urv_Latn": "Urva",
    "urw_Latn": "Urwal",
    "urx_Latn": "Urxela",
    "ury_Latn": "Urya",
    "urz_Latn": "Urza",
    "usa_Latn": "Usaltekhtik",
    "usb_Latn": "Usborne",
    "usc_Latn": "Usconsin",
    "usd_Latn": "Usdan",
    "use_Latn": "Usene",
    "usf_Latn": "Usar",
    "usg_Latn": "Usgan",
    "ush_Latn": "Ushans",
    "usi_Latn": "Usipingtonese",
    "usj_Latn": "Usjavka",
    "usk_Latn": "Uskara",
    "usl_Latn": "Uslan",
    "usm_Latn": "Usmak",
    "usn_Latn": "Uson",
    "uso_Latn": "Usone",
    "usp_Latn": "Uspanteko",
    "usq_Latn": "Usque",
    "usr_Latn": "Usarufa",
    "uss_Latn": "Usser",
    "ust_Latn": "Ustain",
    "usu_Latn": "Usui",
    "usv_Latn": "Usval",
    "usw_Latn": "Usway",
    "usx_Latn": "Usixan",
    "usy_Latn": "Usyalia",
    "usz_Latn": "Uszali",
    "uta_Latn": "Utaina",
    "utb_Latn": "Utbia",
    "utc_Latn": "Ute",
    "utd_Latn": "Utdygutonomy",
    "ute_Latn": "Ute",
    "utf_Latn": "Utfu",
    "utg_Latn": "Utgan",
    "uth_Latn": "Uthman",
    "uti_Latn": "Utian",
    "utj_Latn": "Utjya",
    "utk_Latn": "Utkana",
    "utl_Latn": "Utlen",
    "utm_Latn": "Utami",
    "utn_Latn": "Utone",
    "uto_Latn": "Uto",
    "utp_Latn": "Utopia",
    "utq_Latn": "Utque",
    "utr_Latn": "Utra",
    "uts_Latn": "Utsaa",
    "utt_Latn": "Uttan",
    "utu_Latn": "Utu",
    "utv_Latn": "Utva",
    "utw_Latn": "Utwa",
    "utx_Latn": "Utxela",
    "uty_Latn": "Utya",
    "utz_Latn": "Utzel",
    "uua_Latn": "Uuguada",
    "uub_Latn": "Uubingaji",
    "uuc_Latn": "Uuchukunka",
    "uud_Latn": "Uudhi",
    "uue_Latn": "Uuele",
    "uuf_Latn": "Uufela",
    "uug_Latn": "Uuganja",
    "uuh_Latn": "Uuha",
    "uui_Latn": "Uuimi",
    "uuj_Latn": "Uujinja",
    "uuk_Latn": "Uuka",
    "uul_Latn": "Uulunga",
    "uum_Latn": "Uuma",
    "uun_Latn": "Uunama",
    "uuo_Latn": "Uuomba",
    "uup_Latn": "Uupama",
    "uuq_Latn": "Uuque",
    "uur_Latn": "Uura",
    "uus_Latn": "Uusa",
    "uut_Latn": "Uutala",
    "uuu_Latn": "Uuva",
    "uuv_Latn": "Uuva",
    "uuw_Latn": "Uuwaa",
    "uux_Latn": "Uuxa",
    "uuy_Latn": "Uuya",
    "uuz_Latn": "Uuza",
    "uva_Latn": "Uvacana",
    "uvh_Latn": "Uvhatana",
    "uvl_Latn": "Uvulani",
    "uwa_Latn": "Uwa",
    "uwe_Latn": "Uwera",
    "uwf_Latn": "Uwf",
    "uwh_Latn": "Uwha",
    "uwk_Latn": "Uwika",
    "uwl_Latn": "Uwuli",
    "uwm_Latn": "Uwmbi",
    "uwn_Latn": "Unwera",
    "uwo_Latn": "Uwore",
    "uwp_Latn": "Uwapara",
    "uwr_Latn": "Uwara",
    "uws_Latn": "Uwsa",
    "uwu_Latn": "Uwu",
    "uwv_Latn": "Uwva",
    "uww_Latn": "Uwwa",
    "uwx_Latn": "Uwxa",
    "uwy_Latn": "Uwya",
    "uwz_Latn": "Uwza",
    "uxa_Latn": "Uxal",
    "var_Latn": "Varamin",
    "ved_Latn": "Vedic",
    "vep_Latn": "Veps",
    "vie_Latn": "Vietnamese",
    "vif_Latn": "Vifipa",
    "vig_Latn": "Vigoa",
    "vil_Latn": "Vilela",
    "vim_Latn": "Vimba",
    "vin_Latn": "Vinza",
    "vip_Latn": "Vipnoningo",
    "vis_Latn": "Visayan",
    "vit_Latn": "Vita",
    "viv_Latn": "Viyaya",
    "vkg_Latn": "Vagura",
    "vkj_Latn": "Vakjöski",
    "vkk_Latn": "Vakka",
    "vkl_Latn": "Valkhof",
    "vkm_Latn": "Vakajösk",
    "vko_Latn": "Vakoa",
    "vkp_Latn": "Vakpala",
    "vkr_Latn": "Valkhyr",
    "vks_Latn": "Valkhus",
    "vkt_Latn": "Vakta",
    "vku_Latn": "Vakula",
    "vkv_Latn": "Vakvali",
    "vkw_Latn": "Vakwa",
    "vkx_Latn": "Vakxa",
    "vky_Latn": "Vakya",
    "vkz_Latn": "Vakza",
    "vlp_Latn": "Valpai",
    "vls_Latn": "Vlaams",
    "vlw_Latn": "Vlach",
    "vma_Latn": "Vmandara",
    "vmb_Latn": "Vmba",
    "vmc_Latn": "Vmc",
    "vmd_Latn": "Vmda",
    "vme_Latn": "Vme",
    "vmf_Latn": "Vmfa",
    "vmg_Latn": "Vmga",
    "vmh_Latn": "Vmha",
    "vmi_Latn": "Vmia",
    "vmj_Latn": "Vmja",
    "vmk_Latn": "Vmka",
    "vml_Latn": "Vml",
    "vmm_Latn": "Vmma",
    "vmn_Latn": "Vmna",
    "vmo_Latn": "Ambrym",
    "vmp_Latn": "Vmpa",
    "vmq_Latn": "Vmqa",
    "vmr_Latn": "Vmra",
    "vms_Latn": "Vmsa",
    "vmu_Latn": "Vmua",
    "vmv_Latn": "Vmva",
    "vmw_Latn": "Vmwa",
    "vmx_Latn": "Vmxa",
    "vmy_Latn": "Vmya",
    "vmz_Latn": "Vmza",
    "vnk_Latn": "Vinka",
    "vnm_Latn": "Vinmavis",
    "vnn_Latn": "Vinnan",
    "vnp_Latn": "Vinipan",
    "vns_Latn": "Vinsan",
    "vnt_Latn": "Vintan",
    "vnu_Latn": "Vanuanu",
    "vnw_Latn": "Vanuma",
    "vnx_Latn": "Vinxa",
    "vny_Latn": "Vinye",
    "vnz_Latn": "Vinza",
    "vom_Latn": "Voma",
    "von_Latn": "Vonda",
    "vos_Latn": "Volapük",
    "vot_Latn": "Votic",
    "vov_Latn": "Vovin",
    "vow_Latn": "Vowel",
    "vox_Latn": "Voxa",
    "voy_Latn": "Voyama",
    "voz_Latn": "Vozuwa",
    "vro_Latn": "Võro",
    "vrs_Latn": "Varisi",
    "vrt_Latn": "Varti",
    "vru_Latn": "Varua",
    "vrw_Latn": "Varwa",
    "vsv_Latn": "Vlei",
    "vto_Latn": "Vitou",
    "vum_Latn": "Vumbu",
    "vun_Latn": "Vunjo",
    "vut_Latn": "Vute",
    "vwa_Latn": "Vwaa",
    "waa_Latn": "Waa",
    "wab_Latn": "Wab",
    "wac_Latn": "Waca",
    "wad_Latn": "Wadai",
    "wae_Latn": "Walser",
    "waf_Latn": "Waffa",
    "wag_Latn": "Wa",
    "wah_Latn": "Waha",
    "wai_Latn": "Waiwai",
    "waj_Latn": "Waja",
    "wak_Latn": "Waka",
    "wal_Ethi": "Wolaitta",
    "wam_Latn": "Wampanoag",
    "wan_Latn": "Wana",
    "wao_Latn": "Wao",
    "wap_Latn": "Wappo",
    "waq_Latn": "Waqa",
    "war_Latn": "Waray",
    "was_Latn": "Washo",
    "wat_Latn": "Wata",
    "wau_Latn": "Waura",
    "wav_Latn": "Wava",
    "waw_Latn": "Waiwai",
    "wax_Latn": "Waxa",
    "way_Latn": "Wayana",
    "waz_Latn": "Waza",
    "wba_Latn": "Waamba",
    "wbb_Latn": "Wabby",
    "wbc_Latn": "Wabc",
    "wbd_Latn": "Wabdy",
    "wbe_Latn": "Wabe",
    "wbf_Latn": "Wabf",
    "wbg_Latn": "Wabga",
    "wbh_Latn": "Wabha",
    "wbi_Latn": "Wabii",
    "wbj_Latn": "Wabja",
    "wbk_Latn": "Wabka",
    "wbl_Latn": "Wablul",
    "wbm_Latn": "Wabma",
    "wbn_Latn": "Wabna",
    "wbo_Latn": "Waboo",
    "wbp_Latn": "Walpiri",
    "wbq_Latn": "Wabqa",
    "wbr_Latn": "Wabra",
    "wbs_Latn": "Wabsa",
    "wbt_Latn": "Wabta",
    "wbu_Latn": "Wabua",
    "wbv_Latn": "Wabva",
    "wbw_Latn": "Wabwa",
    "wbx_Latn": "Wabxa",
    "wby_Latn": "Wabya",
    "wbz_Latn": "Wabza",
    "wca_Latn": "Wcaa",
    "wha_Latn": "Whaa",
    "whi_Latn": "Whii",
    "who_Latn": "Whoo",
    "why_Latn": "Whya",
    "wib_Latn": "Wibon",
    "wic_Latn": "Wiccon",
    "wid_Latn": "Widon",
    "wie_Latn": "Wieon",
    "wif_Latn": "Wifon",
    "wig_Latn": "Wigon",
    "wih_Latn": "Wihon",
    "wii_Latn": "Wiion",
    "wij_Latn": "Wijon",
    "wik_Latn": "Wikung",
    "wil_Latn": "Wilon",
    "wim_Latn": "Wimon",
    "win_Latn": "Winon",
    "wio_Latn": "Wioon",
    "wip_Latn": "Wipon",
    "wiq_Latn": "Wiqon",
    "wir_Latn": "Wiron",
    "wis_Latn": "Wison",
    "wit_Latn": "Witon",
    "wiu_Latn": "Wiuon",
    "wiv_Latn": "Wivon",
    "wiw_Latn": "Wiwon",
    "wix_Latn": "Wixon",
    "wiy_Latn": "Wiyon",
    "wiz_Latn": "Wizon",
    "wja_Latn": "Wja",
    "wjy_Latn": "Wajya",
    "wka_Latn": "Wka",
    "wkb_Latn": "Wkab",
    "wkd_Latn": "Wakde",
    "wki_Latn": "Wki",
    "wkl_Latn": "Wikoli",
    "wkr_Latn": "Wkara",
    "wks_Latn": "Wkas",
    "wku_Latn": "Wku",
    "wkw_Latn": "Wakaw",
    "wky_Latn": "Wky",
    "wla_Latn": "Wla",
    "wlc_Latn": "Wellish",
    "wle_Latn": "Wle",
    "wlg_Latn": "Wlag",
    "wli_Latn": "Wli",
    "wlk_Latn": "Wolk",
    "wll_Latn": "Walli",
    "wlm_Latn": "Wlam",
    "wln_Latn": "Wolong",
    "wlo_Latn": "Wolo",
    "wlr_Latn": "Wolar",
    "wls_Latn": "Wallisian",
    "wlu_Latn": "Wulu",
    "wlv_Latn": "Wulvu",
    "wlw_Latn": "Wolwa",
    "wlx_Latn": "Wolxa",
    "wly_Latn": "Wolya",
    "wlz_Latn": "Wolza",
    "wma_Latn": "Wma",
    "wmb_Latn": "Wamba",
    "wmc_Latn": "Wmaaca",
    "wmd_Latn": "Wmada",
    "wme_Latn": "Wmae",
    "wmh_Latn": "Wmaha",
    "wmi_Latn": "Wmaii",
    "wmk_Latn": "Wmak",
    "wmm_Latn": "Wmama",
    "wmn_Latn": "Wmana",
    "wmo_Latn": "Wmao",
    "wms_Latn": "Wmas",
    "wmt_Latn": "Wmata",
    "wmw_Latn": "Wmawa",
    "wmx_Latn": "Wmaxa",
    "wmy_Latn": "Wmaya",
    "wmz_Latn": "Wmaza",
    "wnb_Latn": "Wanambre",
    "wnc_Latn": "Wanc",
    "wnd_Latn": "Wandje",
    "wne_Latn": "Wone",
    "wng_Latn": "Wangang",
    "wni_Latn": "Winiar",
    "wnk_Latn": "Wink",
    "wnm_Latn": "Wanuma",
    "wnn_Latn": "Winnun",
    "wno_Latn": "Wano",
    "wnp_Latn": "Wanap",
    "wnr_Latn": "Wanaran",
    "wns_Latn": "Wans",
    "wnu_Latn": "Wanu",
    "wnw_Latn": "Wanwa",
    "wnx_Latn": "Wanxa",
    "wny_Latn": "Wanya",
    "wnz_Latn": "Wanza",
    "woa_Latn": "Woa",
    "wob_Latn": "Wobeti",
    "woc_Latn": "Woca",
    "wod_Latn": "Woda",
    "woe_Latn": "Woe",
    "wof_Latn": "Wof",
    "wog_Latn": "Woga",
    "woh_Latn": "Woha",
    "woi_Latn": "Woi",
    "woj_Latn": "Woja",
    "wok_Latn": "Woka",
    "wol_Latn": "Wolof",
    "wom_Latn": "Woma",
    "won_Latn": "Wona",
    "woo_Latn": "Woo",
    "wop_Latn": "Wopa",
    "woq_Latn": "Woqa",
    "wor_Latn": "Wora",
    "wos_Latn": "Wosa",
    "wot_Latn": "Wota",
    "wou_Latn": "Woua",
    "wow_Latn": "Wowa",
    "wox_Latn": "Woxa",
    "woy_Latn": "Woya",
    "woz_Latn": "Woza",
    "wpa_Latn": "Wpa",
    "wpb_Latn": "Wpab",
    "wpc_Latn": "Wpac",
    "wpd_Latn": "Wpad",
    "wpe_Latn": "Wpae",
    "wpf_Latn": "Wpaf",
    "wpg_Latn": "Wpag",
    "wph_Latn": "Wpah",
    "wpi_Latn": "Wpii",
    "wpj_Latn": "Wpaj",
    "wpk_Latn": "Wpak",
    "wpl_Latn": "Wpal",
    "wpm_Latn": "Wpam",
    "wpn_Latn": "Wpan",
    "wpo_Latn": "Wpao",
    "wpp_Latn": "Wpap",
    "wpq_Latn": "Wpaq",
    "wpr_Latn": "Wpar",
    "wps_Latn": "Wpas",
    "wpt_Latn": "Wpat",
    "wpu_Latn": "Wpau",
    "wpv_Latn": "Wpav",
    "wpw_Latn": "Wpaw",
    "wpx_Latn": "Wpax",
    "wpy_Latn": "Wpay",
    "wpz_Latn": "Wpaz",
    "wra_Latn": "Wra",
    "wrb_Latn": "Wrab",
    "wrc_Latn": "Wrc",
    "wrd_Latn": "Wrad",
    "wre_Latn": "Wre",
    "wrf_Latn": "Wraf",
    "wrg_Latn": "Wrag",
    "wrh_Latn": "Wrah",
    "wri_Latn": "Wrii",
    "wrj_Latn": "Wraj",
    "wrk_Latn": "Wrak",
    "wrl_Latn": "Wral",
    "wrm_Latn": "Wram",
    "wrn_Latn": "Wran",
    "wro_Latn": "Wro",
    "wrp_Latn": "Wrap",
    "wrq_Latn": "Wraq",
    "wrr_Latn": "Wrar",
    "wrs_Latn": "Wras",
    "wrt_Latn": "Wrat",
    "wru_Latn": "Wrau",
    "wrv_Latn": "Wrav",
    "wrw_Latn": "Wraw",
    "wrx_Latn": "Wrax",
    "wry_Latn": "Wray",
    "wrz_Latn": "Wraz",
    "wsa_Latn": "Wsa",
    "wsb_Latn": "Wabs",
    "wsc_Latn": "Wsc",
    "wsd_Latn": "Wsad",
    "wse_Latn": "Wse",
    "wsf_Latn": "Wsefu",
    "wsg_Latn": "Wsg",
    "wsh_Latn": "Wsha",
    "wsi_Latn": "Wsii",
    "wsk_Latn": "Wsak",
    "wsl_Latn": "Wsal",
    "wsm_Latn": "Wsam",
    "wsn_Latn": "Wsan",
    "wso_Latn": "Wso",
    "wsp_Latn": "Wsap",
    "wsr_Latn": "Wsar",
    "wss_Latn": "Wsas",
    "wst_Latn": "Wsat",
    "wsu_Latn": "Wsau",
    "wsv_Latn": "Wsav",
    "wsw_Latn": "Wsaw",
    "wsx_Latn": "Wsax",
    "wsy_Latn": "Wsay",
    "wsz_Latn": "Wsaz",
    "wta_Latn": "Wta",
    "wtb_Latn": "Wtab",
    "wtd_Latn": "Wtad",
    "wte_Latn": "Wte",
    "wtf_Latn": "Wtaf",
    "wtg_Latn": "Wtag",
    "wth_Latn": "Wtah",
    "wti_Latn": "Wtii",
    "wtj_Latn": "Wtaj",
    "wtk_Latn": "Wtak",
    "wtm_Latn": "Wtam",
    "wtn_Latn": "Wtan",
    "wto_Latn": "Wto",
    "wtp_Latn": "Wtap",
    "wtq_Latn": "Wtaq",
    "wtr_Latn": "Wtar",
    "wts_Latn": "Wtas",
    "wtt_Latn": "Wtat",
    "wtu_Latn": "Wtau",
    "wtv_Latn": "Wtav",
    "wtw_Latn": "Wtaw",
    "wtx_Latn": "Wtax",
    "wty_Latn": "Wtay",
    "wtz_Latn": "Wtaz",
    "wua_Latn": "Wua",
    "wub_Latn": "Wub",
    "wud_Latn": "Wud",
    "wue_Latn": "Wuea",
    "wuf_Latn": "Wufa",
    "wug_Latn": "Wuga",
    "wuh_Latn": "Wuha",
    "wui_Latn": "Wuii",
    "wuj_Latn": "Wuja",
    "wuk_Latn": "Wuka",
    "wul_Latn": "Wula",
    "wum_Latn": "Wuma",
    "wun_Latn": "Wuna",
    "wuo_Latn": "Wuo",
    "wup_Latn": "Wupa",
    "wuq_Latn": "Wuqa",
    "wur_Latn": "Wura",
    "wus_Latn": "Wusa",
    "wut_Latn": "Wuta",
    "wuu_Latn": "Chinese (Shanghainese)",
    "wuv_Latn": "Wuva",
    "wuw_Latn": "Wuwa",
    "wux_Latn": "Wuxa",
    "wuy_Latn": "Wuya",
    "wuz_Latn": "Wuza",
    "wwa_Latn": "Wwa",
    "wwb_Latn": "Wwb",
    "wwc_Latn": "Wwc",
    "wwd_Latn": "Wwd",
    "wwe_Latn": "Wwe",
    "wwf_Latn": "Wwf",
    "wwg_Latn": "Wwg",
    "wwh_Latn": "Wwh",
    "wwi_Latn": "Wwi",
    "wwj_Latn": "Wwj",
    "wwr_Latn": "Wwr",
    "wws_Latn": "Wws",
    "wwt_Latn": "Ww" }

def get_all_languages():
    """Return all supported NLLB-200 languages"""
    languages = []
    for code in sorted(LANGUAGE_NAMES.keys()):
        languages.append({"code": code, "name": LANGUAGE_NAMES[code]})
    return languages

# Map common language codes to NLLB codes
LANGDETECT_TO_NLLB = {
    "en": "eng_Latn",
    "hi": "hin_Deva",
    "fr": "fra_Latn",
    "de": "deu_Latn",
    "es": "spa_Latn",
    "pt": "por_Latn",
    "ru": "rus_Cyrl",
    "it": "ita_Latn",
    "ja": "jpn_Jpan",
    "ko": "kor_Hang",
    "zh-cn": "zho_Hans",
    "zh-tw": "zho_Hant",
    "ar": "arb_Arab",
    "th": "tha_Thai",
    "vi": "vie_Latn",
    "bn": "ben_Beng",
    "ta": "tam_Taml",
    "te": "tel_Telu",
    "ml": "mal_Mlym",
    "kn": "kan_Knda",
    "mr": "mar_Deva",
    "gu": "guj_Gujr",
    "pa": "pan_Guru",
    "ur": "urd_Arab",
    "tr": "tur_Latn",
    "pl": "pol_Latn",
    "nl": "nld_Latn",
    "sv": "swe_Latn",
    "no": "nno_Latn",
    "da": "dan_Latn",
    "fi": "fin_Latn",
    "cs": "ces_Latn",
    "sk": "slk_Latn",
    "hu": "hun_Latn",
    "ro": "ron_Latn",
    "el": "ell_Grek",
    "he": "heb_Hebr",
    "id": "ind_Latn",
    "tl": "tgl_Latn",
    "th": "tha_Thai",
    "ta": "tam_Taml",
    "te": "tel_Telu",
}

def detect_language(text):
    """Detect the language of the input text and return NLLB language code"""
    try:
        # Use langdetect to detect language
        detected_lang = detect(text)
        
        # Map to NLLB code
        nllb_code = LANGDETECT_TO_NLLB.get(detected_lang)
        
        if nllb_code:
            return nllb_code
        else:
            # If exact match not found, try to find partial match
            for key, value in LANGDETECT_TO_NLLB.items():
                if key.startswith(detected_lang):
                    return value
            # Default to English if not found
            return "eng_Latn"
    except LangDetectException:
        # If detection fails, return None
        return None

def translate_text(text, src_lang, tgt_lang):
    tokenizer.src_lang = src_lang
    
    inputs = tokenizer(text, return_tensors="pt")
    
    generated_tokens = model.generate(
        **inputs,
        forced_bos_token_id=tokenizer.convert_tokens_to_ids(tgt_lang)
    )
    
    return tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]